server:
  port: 8183
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-exception: false
    include-message: never

spring:
  application:
    name: reactive-order-service
  datasource:
    url: jdbc:h2:mem:///me

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
