DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL
);
