DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL
);

INSERT INTO ORDERS (USER_ID, PRODUCT_ID, QUANTITY, STATUS) VALUES
(101, 1, 2, 'COMPLETED'),
(102, 3, 1, 'PENDING'),
(101, 2, 5, 'SHIPPED'),
(103, 1, 1, 'COMPLETED'),
(104, 4, 3, 'PENDING');
