server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    # specify not to follow the default git approach 
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
          
        # In production a more common approach is referring to another repo, like ... 
        # git:
        #  uri: https://github.com/<ORG>/<CONFIG-REPO>
        #  default-label: main
