server:
  port: 8483
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-exception: false
    include-message: never

resilience4j:
  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
  circuitbreaker:
    instances:
      userService:
        sliding-window-size: 10                    # number of calls
        failure-rate-threshold: 50                 # failure percentage
        slow-call-rate-threshold: 50               # slow percentage
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
