server:
  port: 8281

user:
    property: xyz

management:
  endpoints:
    web:
      exposure:
        include: refresh  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
