server:
  port: 8283
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-exception: false
    include-message: never

resilience4j:
  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
